=== ks-no/fiks-io-bekymringsmelding-protokoll/schema/domain/v2/privat.bekymringsmelding.v2.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://fiks.ks.no/bekymringsmelding.privat.v2.json",
  "title": "Privat bekymringsmelding",
  "type": "object",
  "required": [
    "kommunenummer",
    "kommunenavn",
    "bydelsnummer",
    "bydelsnavn",
    "privatMelder",
    "privatBarn",
    "melding",
    "sendingstidspunkt",
    "leveringskanal"
  ],
  "properties": {
    "kommunenummer": {
      "type": "string",
      "pattern": "^\\d{4}$"
    },
    "kommunenavn": {
      "type": "string"
    },
    "bydelsnummer": {
      "type": "string",
      "pattern": "^[0-9]{2}$"
    },
    "bydelsnavn": {
      "type": "string"
    },
    "privatMelder": {
      "type": "object",
      "required": [
        "personnavn"
      ],
      "properties": {
        "personnavn": {
          "type": "string"
        },
        "telefonnummer": {
          "type": "string",
          "pattern": "^[+]?[0-9]+([- ][0-9]+)*$"
        },
        "adresse": {
          "$ref": "../adresse.json"
        }
      }
    },
    "privatBarn": {
      "type": "array",
      "minLength": 1,
      "items": {
        "type": "object",
        "required": [
          "personnavn",
          "adresse"
        ],
        "properties": {
          "personnavn": {
            "type": "string"
          },
          "antattAlder": {
            "type": "string"
          },
          "relasjon": {
            "type": "string"
          },
          "adresse": {
            "$ref": "../adresse.json"
          }
        }
      }
    },
    "melding": {
      "type": "string"
    },
    "sendingstidspunkt": {
      "type": "string",
      "format": "date-time"
    },
    "leveringskanal": {
      "type": "string"
    }
  }
}

=== ks-no/fiks-io-bekymringsmelding-protokoll/schema/examples/privatBekymringsmelding.json
{
  "kommunenummer": "1201",
  "kommunenavn": "Bergen",
  "bydelsnummer": "02",
  "bydelsnavn": "Bergenhus",
  "privatMelder": {
    "fnr": "22078347825",
    "personnavn": "Navnesen Navn Mellomnavn",
    "telefonnummer": "99999999",
    "skjultIdentitet": true,
    "adresse": {
      "adresselinje1": "Rosenkrantzgaten 3",
      "adresselinje2": "",
      "adresselinje3": "",
      "postnummer": "5003",
      "poststed": "Bergen"
    }
  },
  "privatBarn": [
    {
      "personnavn": "Barn Barnesen",
      "antattAlder": "10",
      "relasjon": "Nabo, fritekstfelt",
      "adresse": {
        "adresselinje1": "RÃ¥dhusgaten 10",
        "adresselinje2": "",
        "adresselinje3": "",
        "postnummer": "5020",
        "poststed": "Bergen"
      }
    },
    {
      "personnavn": "Bare Barnet",
      "antattAlder": "10",
      "relasjon": "Nabo, fritekstfelt",
      "adresse": {
        "adresselinje1": "RÃ¥dhusgaten 10",
        "adresselinje2": "",
        "adresselinje3": "",
        "postnummer": "5020",
        "poststed": "Bergen"
      }
    }
  ],
  "melding": "Her kommer selve innholdet i bekymringsmeldingen!",
  "sendingstidspunkt": "2020-03-17T00:31:56",
  "leveringskanal": "Fagsystem"
}
